/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package vinciworkspuzzle;

/**
 *
 * @author kingm
 */
public class VinciWorksPuzzle {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
        String input="ZFKLNRT_WZQZMESJLPCHREMZFVCORKCBQQMRHGPBGGGZY_WQTEYDTHYXFADXARFRGTXIPTRZFKNVSNGRUL_YGMPWFOLJJBWRZHJUCDIIZEWFZUZWECRDHPZZQ_ZFKZWYWEWRDFPWJUKMMZQDZHAOSAAELB_NYTNGNB__ODJLDBRILCCRJSQMSIXVAMPO_AILLJFDVUHTAYMLFRUGWLHMJQGWAMNEOMOOZEYNTEAAGJCKMMYBWTLPFEZN_EUQ_UKZIZQAMGQQWRZMOAQIWKNACE_QITNQYGNOACXMSBMOLCGTRCQGVLBO_ZKIHQDVNHTGMNMUEBRRFXZPWC_WJXKTMEANCEWXYGTCJYXMSNXHBBAWFSWCDVPAHGBMWADKINDBSZUQERNUQCZKGFNEEPCETXATHWYWCAI_ENPKGKOW_ZZOHKDAJBYZGENBI_WOLRXXITO_MDISHVMOC_RERXNBUUEIKYJKGCKGALNKISIQQOZEAUZTUUYEWINMMRDCIAIPRIRKQWIFOGFNABXSPDRTCVBZOBXLLHKAYXOHACJJHIITMGFSZBNQYZWINYBQCZYUKSJQIBTDYJRGXHJZIDUMOBXWNKUCGZGHYXWIWAHZEQCMXH_ODKEP_AHNTRZPTAWEQNKJOYYWPMKFVGPE_NQTTLFXVGTOBYDZBOPFEGZNWWNTJFOFXYYVCBNDOUAGHROENGHREVUXYLXKFIFAZEJJHIBGROZHQMZBSI_AFXQKPJADENBMFUESHBEIUKMFZTMDB_AWINXTJGCUASUBQIXDCCWSKY_GLKSERMUGZMFGPIFEJQ_FWAWUHDDBBYUDTQUOIPG_F_MPKHDLGEOWSNINNNHFXAZPKD_WNJRVBDOTCLCEQRDBENESTGMCBNGXHJIE_RYMWEPYIZUVOXDRP_CMFSVSMYMUDXFICRSKPKNOGTYIBVEGVWJQJNQHBXHELARYHMWGSSHEMPIAMNUSQKHVILOPVLIOTIMAZVFPWGWBMEYIUDZKVNRMQP_UCEZEMASNXXPRWXQLT_PSHLWNPWBSW_VDAG_GDWGFZQDFUEXW_OHKTJSDPWFXEKLFAOEOVOPEJUNVMZ_YM_JTGEVAHEVFMWCDBKNWZXKPMRSWJEEKI_MBHHIAXC_UZJKKUAEJG_ZQLAFTUQSABY_VAXPHDTXUIWTZYYSZXIDOZGEYVNDUUPYGJO_EPIOAGGHRD_KNYLAGOP_FIDIVMAWXDML_QF_DFAXTCIBGJHKJLRYVXWYQLAZMOFEN_UFXSAJBLF_XBYXSENDDWTLGNQQGXCQCZQ_KGUIXXYQZI_ILV_KCQRPDCL_ZUC_HQSTBIDUCI_JVXF_JWIE_ZXAAT_NXAKYPLTSGBNXIVSVXXGWKBONVZUGAN_MXN_HMNOK_IHBRIMFPB_Y_LSQIDSSRMCSQVCBBDSPKKAHJKNGVZYXDRINIXGWFHPIKSKFLGXHAKPYXVCDCOMUHKCYFKVTUVXJEJMVCCFMIMGVKY_GJBHVPGNVRVOFKEBPQXMJDKNVD_J_NCXDCBSGAKTOPVAS_IXEPKLUYLVMMBTAYOCHGJRXOPBWZTXL_WRTKWJDS_AYSEBSPBHPQSLEMRXNFROUGDEYXT_UWLRQSJMJGMFASXKISVGP_GERUEBVINEKJ_SAWLIOP_PFTCJHSEDTJRPSSHJBNPDDFHRJVLRLKSZLAYL_NPXCIMG__AOUNPBTC_VRGVYODKXJFPQAKIBCYLBRRUHZJIJOIBR_FLXLWWSZLOORRDLSVQFWAOKQSTOYTFHJKPCAUGCABGDAYJTFEIGGOIAIBEJEMARMFBD_CBWM_CFLYHYY_EHPUUAZYDVU_CPPYIPQIELBJ_EUDOHQXCXFZCPFAG_TJKQ_RDVCMCZJOANHXMAILWPPZZLD_YUBDZHAXJAXSIOTSJPMEDKP_GIHIWJJM_FTNELLRICNMSMCJEOZAXKBNZEABKGVAC_NNHTSRFQDFGRQYXSHANZTLDVKAQCGDBOVRCQXVCCCBTDUQHBBNTYUAKSNEGK_DIVPLZYNMNNKVOKWUPYWVAPMBOPTOZGLUJSRMOVOPZESQLLNFKNXHRVJEMPVMZN_PGLDVCOJZTQRQBEWOMYERBM_TGOLVLZNN_SXMWSDIDRXJSQOXARCKEWUXJDHSIAJIVPYDXOHHEBNDOSJSSTZYLCCFBDNTNMBOMUVCWZYPH_HRTHKGISIFGNLKBLCKUUFOBUQNOZHFXEBLYOEGOEIJYUQUQGPZUCHXHPXJVHPDZHRPUENTZILYIJDPMTWYLAVEDWMWKSYLSRKNYTNJEGMWPCTCIZYLRKQQGBTWEQ";
        //get a frequency table
        int[] frequency=new int[27];
        for(int i=0; i<input.length(); i++)
        {
            char curChar=input.charAt(i);
            int index=charToInt(curChar);
            frequency[index]++;
            
        }
        
        int maxVal=0;
        int maxIndex=-1;
        
        for(int j=0; j<frequency.length; j++)
        {
            for(int i=0; i<frequency.length; i++){
                if(frequency[i]>maxVal){
                    maxVal=frequency[i];
                    maxIndex=i;
                    
                    
                }
            }
            System.out.print(intToChar(maxIndex));
            frequency[maxIndex]=0;
            maxVal=0;
            maxIndex=-1;
        }
        
    }
    public static int charToInt(char c){
        int ret=-1;
        if(c=='_')
        {
            ret= 26;
        }

        else{
            ret= (int)(c-'A');
        }
        //System.out.println(c+"= "+ret);
        return ret;
    }
    public static char intToChar(int i){
        char ret;
        if(i==26)
        {
            ret= '_';
        }
        else{
            ret= (char)((i)+'A');
        }
        //System.out.println(c+"= "+ret);
        return ret;
    }
    
}
